version: '3'

services:
  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    container_name: postgres
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: Passw0rd
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    container_name: redis
    volumes:
      - "./docker/redis/data:/data"
