create role user1 login password 'USER1';
create database demo with owner = user1;
grant all privileges on database demo to user1;
\c demo
CREATE TABLE users(
    id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password  character varying(1000) NOT NULL,
    name      character varying(1000) NOT NULL,
    create_date timestamp NOT NULL,
    update_date timestamp NOT NULL,
    version   bigint NOT NULL
);
ALTER TABLE public.users OWNER TO user1;
